# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1125, 582)
        font = QtGui.QFont()
        font.setFamily("汉仪力量黑简")
        font.setKerning(True)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(False)
        self.toolButton = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton.setGeometry(QtCore.QRect(20, 160, 181, 61))
        self.toolButton.setStyleSheet("color: rgb(54, 102, 250);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"汉仪力量黑简\";")
        self.toolButton.setAutoRaise(False)
        self.toolButton.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_2.setGeometry(QtCore.QRect(20, 230, 181, 61))
        self.toolButton_2.setMouseTracking(False)
        self.toolButton_2.setTabletTracking(False)
        self.toolButton_2.setAcceptDrops(False)
        self.toolButton_2.setAutoFillBackground(False)
        self.toolButton_2.setStyleSheet("color: rgb(54, 102, 250);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"汉仪力量黑简\";")
        self.toolButton_2.setCheckable(False)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_3.setEnabled(True)
        self.toolButton_3.setGeometry(QtCore.QRect(20, 300, 181, 61))
        font = QtGui.QFont()
        font.setFamily("汉仪力量黑简")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setMouseTracking(False)
        self.toolButton_3.setStyleSheet("color: rgb(54, 102, 250);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"汉仪力量黑简\";")
        self.toolButton_3.setCheckable(False)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_4.setEnabled(True)
        self.toolButton_4.setGeometry(QtCore.QRect(20, 370, 181, 61))
        font = QtGui.QFont()
        font.setFamily("汉仪力量黑简")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setMouseTracking(False)
        self.toolButton_4.setStyleSheet("color: rgb(54, 102, 250);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"汉仪力量黑简\";")
        self.toolButton_4.setCheckable(False)
        self.toolButton_4.setObjectName("toolButton_4")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(250, 130, 651, 421))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(160, 20, 421, 91))
        self.label_3.setStyleSheet("font: 9pt \"汉仪力量黑简\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 131, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../.designer/ProiconsBox (1).svg"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pirsm Toolbox"))
        self.toolButton.setText(_translate("Dialog", "搜索玩家"))
        self.toolButton_2.setText(_translate("Dialog", "单独破解"))
        self.toolButton_3.setText(_translate("Dialog", "批量破解"))
        self.toolButton_4.setText(_translate("Dialog", "批量破解（PC端）"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:48pt;\">Pirsm Toolbox</span></p></body></html>"))
